<!doctype html>
<html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin | Minh Wuan Store</title>
<style>
:root{--bg:#f7fbff;--card:#fff;--text:#10223e;--muted:#667892;--line:rgba(15,23,42,.12);--primary:#0068ff;--green:#10b981;--red:#ef4444;--shadow:0 18px 50px rgba(39,77,146,.13);--r:22px}*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,-apple-system,Segoe UI,Arial,sans-serif;background:linear-gradient(180deg,#f7fbff,#fff8fc);color:var(--text)}.container{width:min(1160px,calc(100% - 32px));margin:auto;padding:26px 0 80px}.top{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:20px}.card{background:#fff;border:1px solid var(--line);border-radius:var(--r);box-shadow:var(--shadow);padding:20px;margin-bottom:18px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.row{display:grid;grid-template-columns:1fr 1fr auto;gap:10px;align-items:center;margin-bottom:10px}label{display:grid;gap:6px;font-weight:800;color:#263b5a}input,select,textarea{width:100%;border:1px solid var(--line);border-radius:14px;padding:12px 13px;font:inherit;background:#fff}textarea{min-height:78px;resize:vertical}.btn{border:0;border-radius:999px;padding:12px 16px;font-weight:950;cursor:pointer}.primary{background:linear-gradient(135deg,var(--primary),#36c8ff);color:#fff}.soft{background:rgba(0,104,255,.08);color:var(--primary);border:1px solid rgba(0,104,255,.12)}.danger{background:rgba(239,68,68,.08);color:var(--red);border:1px solid rgba(239,68,68,.16)}.success{background:rgba(16,185,129,.1);color:#0d8f64;border:1px solid rgba(16,185,129,.18)}.actions{display:flex;gap:10px;flex-wrap:wrap}.product-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.product-head img{width:52px;height:52px;border-radius:16px;background:#f1f5f9}.muted{color:var(--muted);line-height:1.55}.hidden{display:none}.price-title{display:flex;justify-content:space-between;align-items:center;margin:12px 0}.toast{position:fixed;left:50%;bottom:24px;transform:translateX(-50%);background:#10223e;color:#fff;border-radius:999px;padding:12px 16px;font-weight:900;display:none}.toast.show{display:block}@media(max-width:760px){.grid,.row{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}}


/* ===== Admin Motion Polish ===== */
.card { animation: adminFadeUp .45s ease both; }
.btn { transition: transform .18s ease, box-shadow .18s ease; }
.btn:hover { transform: translateY(-2px); }
.primary { box-shadow: 0 14px 30px rgba(0,104,255,.18); }
.product-head img { transition: transform .22s ease; }
.product-head img:hover { transform: scale(1.06) rotate(-3deg); }
.toast.show { animation: adminToast .22s ease both; }
@keyframes adminFadeUp { from { opacity: 0; transform: translateY(14px); } to { opacity: 1; transform: translateY(0); } }
@keyframes adminToast { from { opacity: 0; transform: translateX(-50%) translateY(12px); } to { opacity: 1; transform: translateX(-50%) translateY(0); } }
@media (prefers-reduced-motion: reduce) { *, *::before, *::after { animation: none !important; transition: none !important; } }

</style></head><body><div class="container">
<div class="top"><div><h1>Admin Minh Wuan Store</h1><p class="muted">Sửa ngày update, sản phẩm, giá và lưu trực tiếp vào Supabase.</p></div><div class="actions"><a class="btn soft" href="/" target="_blank">Xem trang khách</a><button class="btn danger" id="logout">Đăng xuất</button></div></div>
<section class="card" id="loginBox"><h2>Đăng nhập admin</h2><p class="muted">Mật khẩu nằm trong biến môi trường ADMIN_PASSWORD trên Vercel.</p><div class="grid"><input id="password" type="password" placeholder="Nhập mật khẩu admin"><button class="btn primary" id="loginBtn">Đăng nhập</button></div></section>
<main id="app" class="hidden"><section class="card"><h2>Cài đặt website</h2><div class="grid" id="settingsForm"></div></section><section class="card"><div class="product-head"><div><h2>Sản phẩm</h2><p class="muted">Thêm/xóa/sửa sản phẩm và giá. Bấm lưu để cập nhật cho khách.</p></div><div class="actions"><button class="btn soft" id="addProduct">+ Thêm sản phẩm</button><button class="btn primary" id="saveBtn">Lưu thay đổi</button></div></div></section><div id="products"></div></main></div><div class="toast" id="toast"></div>
<script>
let token=localStorage.getItem("mw_admin_token")||"";let state={settings:{},products:[]};
const settingFields=[["updateDate","Ngày update"],["website","Website"],["zaloBuyUrl","Link Zalo mua hàng"],["zaloGroupUrl","Link nhóm Zalo"],["popupTitle","Tiêu đề popup"],["popupText","Nội dung popup"]];
function uid(prefix="id"){return prefix+"-"+Math.random().toString(36).slice(2,9)}
function esc(s){return String(s||"").replaceAll("&","&amp;").replaceAll('"',"&quot;").replaceAll("<","&lt;")}
function toast(msg){const t=document.getElementById("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2400)}
function authHeaders(){return{"Content-Type":"application/json","Authorization":"Bearer "+token}}
async function login(){const password=document.getElementById("password").value;const res=await fetch("/api/admin-login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});const data=await res.json();if(!res.ok)throw new Error(data.message||"Đăng nhập lỗi");token=data.token;localStorage.setItem("mw_admin_token",token);await load()}
async function load(){const res=await fetch("/api/admin-store",{headers:authHeaders()});const data=await res.json();if(!res.ok)throw new Error(data.message||"Không tải được dữ liệu");state=data;document.getElementById("loginBox").classList.add("hidden");document.getElementById("app").classList.remove("hidden");render()}
function renderSettings(){document.getElementById("settingsForm").innerHTML=settingFields.map(([key,label])=>`<label>${label}<input data-setting="${key}" value="${esc(state.settings[key])}"></label>`).join("")}
function priceRow(x={}){return`<div class="row price-row"><input data-price="label" placeholder="Tên gói" value="${esc(x.label)}"><input data-price="price" placeholder="Giá" value="${esc(x.price)}"><button class="btn danger" data-act="delete-price">Xóa</button></div>`}
function renderProduct(p,i){return`<section class="card product" data-index="${i}"><div class="product-head"><div class="actions"><img src="${esc(p.image_url)}" onerror="this.style.display='none'"><div><h2>${esc(p.name)||"Sản phẩm mới"}</h2><p class="muted">${esc(p.category)} · ${esc(p.badge)}</p></div></div><div class="actions"><button class="btn soft" data-act="duplicate">Nhân bản</button><button class="btn danger" data-act="delete">Xóa</button></div></div><div class="grid"><label>ID<input data-field="id" value="${esc(p.id||uid("product"))}"></label><label>Tên sản phẩm<input data-field="name" value="${esc(p.name)}"></label><label>Danh mục<select data-field="category"><option value="combo">Combo</option><option value="ai">App AI</option><option value="edit">Video / Photo</option><option value="entertainment">Giải trí</option></select></label><label>Nhãn/badge<input data-field="badge" value="${esc(p.badge)}"></label><label>Ảnh/logo URL<input data-field="image_url" value="${esc(p.image_url)}"></label><label>Thứ tự<input type="number" data-field="sort_order" value="${p.sort_order||0}"></label><label><span>Đang bán</span><select data-field="active"><option value="true">Có</option><option value="false">Ẩn</option></select></label><label>Mô tả<textarea data-field="description">${esc(p.description)}</textarea></label></div><div class="price-title"><h3>Giá</h3><button class="btn success" data-act="add-price">+ Thêm dòng giá</button></div><div class="prices">${(p.prices||[]).map(priceRow).join("")}</div></section>`}
function render(){renderSettings();document.getElementById("products").innerHTML=state.products.map(renderProduct).join("");document.querySelectorAll("[data-field='category']").forEach(s=>{const p=state.products[+s.closest(".product").dataset.index];s.value=p.category||"ai"});document.querySelectorAll("[data-field='active']").forEach(s=>{const p=state.products[+s.closest(".product").dataset.index];s.value=String(p.active!==false)})}
function collect(){const settings={};document.querySelectorAll("[data-setting]").forEach(i=>settings[i.dataset.setting]=i.value);const products=[...document.querySelectorAll(".product")].map(card=>{const p={prices:[]};card.querySelectorAll("[data-field]").forEach(i=>{let v=i.value;if(i.dataset.field==="active")v=v==="true";if(i.dataset.field==="sort_order")v=Number(v||0);p[i.dataset.field]=v});card.querySelectorAll(".price-row").forEach((r,idx)=>{const label=r.querySelector("[data-price='label']").value;const price=r.querySelector("[data-price='price']").value;if(label||price)p.prices.push({id:(p.id||uid("p"))+"-"+(idx+1),label:label||"Gói",price:price||"Inbox",sort_order:idx})});return p});return{settings,products}}
async function save(){const payload=collect();const res=await fetch("/api/admin-save-store",{method:"POST",headers:authHeaders(),body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)throw new Error(data.message||data.detail||"Lưu lỗi");state=payload;toast("Đã lưu, trang khách đã cập nhật")}
document.getElementById("loginBtn").onclick=()=>login().catch(e=>toast(e.message));document.getElementById("saveBtn").onclick=()=>save().catch(e=>toast(e.message));document.getElementById("addProduct").onclick=()=>{state=collect();state.products.push({id:uid("product"),name:"Sản phẩm mới",category:"ai",badge:"",description:"",image_url:"",sort_order:999,active:true,prices:[{label:"1 tháng",price:"Inbox"}]});render()};document.getElementById("logout").onclick=()=>{localStorage.removeItem("mw_admin_token");location.reload()};
document.getElementById("products").addEventListener("click",e=>{const btn=e.target.closest("button");if(!btn)return;const card=btn.closest(".product");const act=btn.dataset.act;if(act==="delete"){state=collect();state.products.splice(+card.dataset.index,1);render()}if(act==="duplicate"){state=collect();const copy=JSON.parse(JSON.stringify(state.products[+card.dataset.index]));copy.id=uid(copy.id||"product");copy.name=copy.name+" copy";state.products.push(copy);render()}if(act==="add-price"){card.querySelector(".prices").insertAdjacentHTML("beforeend",priceRow())}if(act==="delete-price"){btn.closest(".price-row").remove()}});
if(token)load().catch(()=>localStorage.removeItem("mw_admin_token"));
</script></body></html>